#!/usr/bin/env bash

set -eou pipefail

MESSAGE=""
COUNT=5

help() {
    echo -e "\nUsage: $0 [OPTION]"
    echo 
    echo -e "\t-m\tmessage to print"
    echo -e "\t-n\tnumber of messages to print. Default 5"
    echo -e "\t-h\tget help"
}

[[ -z "$@" ]] && help && exit 1;

for arg in "$@"; do
    case $arg in
        -m)
            MESSAGE=$2
            shift
            shift
            ;;
        -n)
            COUNT=$2
            shift
            shift
            ;;
        -h)
            help
            exit 0
            ;;
    esac
done

for i in $(seq 1 $COUNT); do
    echo $MESSAGE;
done
