#!/usr/bin/env bash

retfunc() {
    echo "this is retfunc()"
    return 1
}

exitfunc() {
    echo "this is exitfunc()"
    exit 1
}

retfunc
echo "we are still here"

exitfunc
echo "we will never see this"
