#!/usr/bin/env bash

case $1 in
    start)
        echo "start the pc"
        ;;
    stop)
        echo "stop the pc"
        ;;
    restart)
        echo "restart the pc"
        ;;
    *)
        echo "Usage: start|stop|restart pc name"
        ;;
esac
